drop table if exists `user`;

create table user (
	id bigint generated by default as identity,
	username varchar(64) not null,
	age int(1) null,
	password varchar(64) not null,
    primary key (id)
);
