drop table if exists `school`;

create table school (
	id bigint generated by default as identity,
	name varchar(64) not null,
	address varchar(64) not null,
	note varchar(64) not null,
    primary key (id)
);
